version: "3.6"
services:
  web:
    build: .
    container_name: "rushing_to_thescore_web"
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
volumes:
  pgdata:
