name: TEST

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rushing_to_thescore_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
          - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.11.3' # Define the elixir version [required]
        otp-version: '23.x' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: ${{ runner.os }}-mix-
    - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
    - run: mix local.rebar --force
    - run: mix local.hex --force
    - run: mix deps.get
    - run: npm install --prefix assets
    - run: npm run deploy --prefix assets
    - run: mix test
